databases:
  - name: judge_story_app_db
    region: singapore
    plan: free
    databaseName: judge_story_app_db
    user: django_user


services:
  - type: web
    name: judge_story_app
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: judge_story_app_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true