databases:
  - name: steam_review_app_db
    region: singapore
    plan: free
    databaseName: steam_review_app_db
    user: django_user


services:
  - type: web
    name: steam_review_app
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn mysite.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: steam_review_app_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true